name: MultiArchDockerBuild

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  DH_REGISTRY: docker.io
  GH_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  lowercasify:
    runs-on: ubuntu-24.04
    outputs:
      image_name: ${{ steps.image.outputs.image_name }}
      repo_name: ${{ steps.repo.outputs.repo_name }}
    steps:
      - name: Lowercase image name
        id: image
        run: |
          echo "image_name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - name: Lowercase repo name
        id: repo
        run: |
          echo "repo_name=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

  build_x86_image:
    name: Build x86-64 Docker image
    runs-on: ubuntu-24.04
    needs:
      - lowercasify
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ needs.lowercasify.outputs.image_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push release Docker image
        uses: docker/build-push-action@v6
        with:
          target: true
          push: true
          tags: ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}-x86
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
  
  build_arm_image:
    name: Build ARM Docker image
    runs-on: ubuntu-24.04-arm
    needs:
      - lowercasify
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ needs.lowercasify.outputs.image_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push release Docker image
        uses: docker/build-push-action@v6
        with:
          target: true
          push: true
          tags: ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}-ARM
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
  
  combine-images:
    name: Combine Docker images
    runs-on: ubuntu-24.04
    needs:
      - lowercasify
      - build_x86_image
      - build_arm_image
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ needs.lowercasify.outputs.image_name }}
      REPOSITORY: ${{ needs.lowercasify.outputs.repo_name }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define release tag patterns
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          cat << EOF >> "$GITHUB_ENV"
          PIMAGES=${{ env.DOCKER_USERNAME }}/${{ env.REPOSITORY }}
          ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          EOF
          cat << EOF >> "$GITHUB_ENV"
          PTAGS=type=raw,value=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          EOF
      
      - name: Define develop tag patterns
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: |
          cat << EOF >> "$GITHUB_ENV"
          PIMAGES=${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          EOF
          cat << EOF >> "$GITHUB_ENV"
          PTAGS=type=ref,event=branch
          type=ref,event=pr
          EOF
      
      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PIMAGES }}
          tags: ${{ env.PTAGS }}

      - name: Combine JVM images into single manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sources: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}-x86
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}-ARM
