name: MultiArchDockerBuild

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    env:
      DH_REGISTRY: docker.io
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REPOSITORY: ${{ github.event.repository.name }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for release Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKER_USERNAME }}/${{ env.REPOSITORY }}
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Extract metadata for develop Docker image
        if: "!startsWith(github.ref, 'refs/tags/v')"
        id: meta-develop
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          target: deploy
          push: true
          tags: ${{ if(startsWith(github.ref, 'refs/tags/v'), steps.meta.outputs.tags, steps.meta-develop.outputs.tags) }}
          labels: ${{ if(startsWith(github.ref, 'refs/tags/v'), steps.meta.outputs.labels, steps.meta-develop.outputs.labels) }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
